### ISSUE TITLE
Add option to present with audio!

### ISSUE THREAD

**Issue by DillFrescott** [mattermost/mattermost-plugin-calls#127]
This is important for presenting applications and ideas that take advantage of audio.

**Comment by streamer45** [comment]
Hi @DillFrescott ,

I assume you are talking about including audio when screensharing. We have a way of doing that already but it's currently hidden under experimental features since it doesn't work uniformly across platforms. To give it a try you can turn it on by sending the `/call experimental on` slash command.

This is what has been confirmed to work:

- Audio sharing works across platforms when sharing a single Chrome tab. This assumes you are using Chrome browser.
- Sharing system-level audio works on Windows only.

**Comment by DillFrescott** [comment]
Excellent! Thank you!

**Comment by DillFrescott** [comment]
@streamer45 Quick question.

If I enable the experimental call feature, will it present with system audio if I am using the mattermost desktop app for windows?

**Comment by streamer45** [comment]
@DillFrescott 

That would be my expectation although I am not a Windows user but from what I remember when originally testing this feature it worked.
