### ISSUE TITLE
[Feature Requests] option to select shared monitor and phone dial-in

### ISSUE THREAD

**Issue by rtfm98** [mattermost/mattermost-plugin-calls#151]
Hey there,

first of all: this plugin is great!
During our tests in our enterprise environment, we noticed two things that could be improved in our opinion:

- screen sharing: it would be really helpful to have an option to select the monitor to share (when using multiple screens). Otherwise it becomes partly difficult to read the shared content
- nice to have: an option to configure SIP/phone dial-in (like Jigasi for Jitsi Meet)

Best regards!

**Comment by streamer45** [comment]
Hi @rtfm98, thanks for the feedback. 

Regarding your first point I feel you may have tested on a slightly out of date Desktop version because there is indeed a way to select which screen/window to share. However this behaviour is available from 5.1.0 onwards. If that's the case I'd encourage you to upgrade to the latest version and see if it works as you'd expect.

As for dialing from phone (SIP support) that's something on our radar as well and we are seriously considering it for the future.

**Comment by rtfm98** [comment]
Hi @streamer45, thank you very much for your quick response!

You're right: we are still using the v5.0.x Desktop app. However, version 5.1.x is on the way, but we're currently still waiting for the distribution of the GPOs. Can't wait to test screensharing with this version :)

> As for dialing from phone (SIP support) that's something on our radar as well and we are seriously considering it for the future.

Glad to hear that!

I'd close my issue for now and wait for the following releases. Best regards!
