### ISSUE TITLE
Call not ended

### ISSUE THREAD

**Issue by AkramiPro** [mattermost/mattermost-plugin-calls#351]
every one leave the call but the call not ended for 10 day !!!
![Screenshot_2](https://user-images.githubusercontent.com/54323929/222203215-0f94417e-246d-4b73-b065-583a5f9a3896.png)

**Comment by streamer45** [comment]
@AkramiPro Sometimes the calls state can get stuck due to internal issues (e.g. db calls timing out). We are looking into potential solutions like automatically ending a call if less than 2 participants are in after some time. But for now either a sysadmin or the the user that started the call can send the `/call end` slash command to force end it.

**Comment by AkramiPro** [comment]
![image](https://user-images.githubusercontent.com/54323929/222265217-6014d4c3-b20e-48ee-90e3-440fb2ea1eb2.png)

**Comment by AkramiPro** [comment]
![image](https://user-images.githubusercontent.com/54323929/222266707-79439f86-6c74-44cd-a4ab-511ce2d07d50.png)

**Comment by AkramiPro** [comment]
![image](https://user-images.githubusercontent.com/54323929/222266815-1c129478-ed3b-4e46-bb53-710ae04bbd83.png)

**Comment by streamer45** [comment]
Oh wow, that doesn't look good. Is there a chance you could share server logs? Something must be going on preventing the thread from getting updated correctly.

You can reach me internally through a DM on https://community.mattermost.com  (username is `claudio.costa`).

**Comment by streamer45** [comment]
@AkramiPro Mattermost 7.10 is out now which includes a fix for this issue. Closing this now.
