### ISSUE TITLE
Calls overrides the custom udp port?

### ISSUE THREAD

**Issue by redfoxlee** [mattermost/mattermost-plugin-calls#379]
Hi, we had couple issues with this plugin. hope you can help us out. English is not my mother language, but i'll try my best to make it clear.

**Problem**
We deployed our self-hosted enterprise version on AWS and had a calls plugin configured with a standalone RTCD service which uses a custom udp port.

The standalone RTCD service is running on ECS (single node cluster, so dose the mattermost) with couple config environment overrides. It dose not look like this in the real task definition but i'm sure it's not gonna be a problem:-)
```
RTCD_RTC_ICEPORTUDP=<custom udp port>
RTCD_RTC_ICEHOSTOVERRIDE=<xxx.xxx.xxx.xxx>
RTCD_RTC_API_SECURITY_ALLOWSELFREGISTRATION=True
...
(maybe loggers, but it's not important)
```
We confirmed RTCD service has started as expected from the logs.
```
rtc: server is listening on udp: <custom udp port>
```
We also confirmed calls config by calling `/api/v4/config` right after applying changes (seems good, not sure).
```json
"com.mattermost.calls": {
    "allowenablecalls": true,
    "allowscreensharing": true,
    "defaultenabled": true,
    "enablerecordings": false,
    "icehostoverride": "",
    "iceserversconfigs": "",
    "jobserviceurl": null,
    "maxcallparticipants": 0,
    "maxrecordingduration": 60,
    "rtcdserviceurl": "http://rtcd.internal.xx:8045",
    "turncredentialsexpirationminutes": 1440,
    "turnstaticauthsecret": "",
    "udpserverport": null,
    "udpserveraddress": ""
}
```
Once we hit the start button, we observed that the ice candidates port has been overrode to `8443` through the chrome console which leads to a connection failure of cause.
```
com.mattermost.calls: remote signal {"candidate ... udp xxxxxx xxx.xxx.xxx.xxx 8443 typ host" ...
```
Go back to the plugin settings view remove the "RTCD Service URL" and after saving changes, "UDP Sever Port" apears with a default value: `8443`.

**Environment Information**
- mattermost-enterprise-edition 7.8.0
- mattermost-calls 0.14.0
- mattermost-rtcd 0.9.0

**Question**
- Is this a expected behavior?
- or What did i wrong and how can i fix it?

Apology for my bad english!
Thank you for your time.

**Comment by streamer45** [comment]
Hi @redfoxlee,

If you are deploying and using the standalone `rtcd` service several options in the plugin configuration won't apply any longer:

- `udpserveraddress`
- `udpserverport`
- `icehostoverride`
- `iceserversconfigs`
- `turncredentialsexpirationminutes`
- `turnstaticauthsecret`

All of the above have respective counterparts in the `rtcd` [configuration](https://github.com/mattermost/rtcd/blob/2c4d81b3e6726e0734801534d08a90880ae16b14/config/config.sample.toml#L25-L44).

Now, the port that you define as `RTCD_RTC_ICEPORTUDP` is the one that eventually gets relayed to the clients as the main host candidate like the one you showed a log for above. If that's not happening then there must be a problem initializing the service from the plugin side.

Could you share MM server logs when enabling the plugin (or starting the server)?

Also consider joining our [community server](https://community.mattermost.com/) and send me a DM if you'd like to keep logs private. You can find me as `claudio.costa`.

**Comment by redfoxlee** [comment]
Hi @streamer45 
Thanks for the reply!
I'm sorry i forgot to mention one thing in the first place. This must be important. No matter what we do, we always fail to to enable the plugin unless removing *RTCD Service URL*.
```
This plugin failed to start. failed to create rtcd manager: failed to register rtcd client: request failed: registration failed: already registered.
```
It took time to ask for the authorizations, but I've already send you the log files. Note that the MM part is filtered by *com.mattermost.calls*, let me know if you prefer the unfiltered version.

**Comment by streamer45** [comment]
Well that's the real problem then. Sounds like the plugin side got itself locked out somehow. I'd try to stop `rtcd`, remove its persistent storage directory (`/tmp/rtcd_db` if you are using default settings) and restart both `rtcd` service and then plugin.

**Comment by redfoxlee** [comment]
We are running `rtcd`  in a docker container (_AWS ECS_). Is that doable? However, we tried to delete and recreate the container and it didn't work...don't know why

**Comment by streamer45** [comment]
Unless you are persisting the state using a volume then recreating the container should reset the whole thing which should fix that error at least. Are you still getting the same after restarting the plugin on MM?

**Comment by streamer45** [comment]
Had a closer look at the logs you provided, the original error is this one:

```
failed to connect rtcd client: failed to create ws client: failed to dial: Not Found
```

Which is very odd, something is preventing the websocket client from connecting to the `rtcd` host.

**Comment by streamer45** [comment]
@redfoxlee I think there could be an issue with the local DNS resolution for your `rtcd` host. It looks like the MM side may be getting the wrong IP address or the routing is not as expected.

**Comment by streamer45** [comment]
On a second thought, since the HTTP requests seem to be reaching just fine, I wonder if there could be something in between, like a proxy or load balancer that's not properly configured to handle websocket.

**Comment by redfoxlee** [comment]
@streamer45 

Thanks for the reply! Sorry for the late answer.

> Unless you are persisting the state using a volume then recreating the container should reset the whole thing which should fix that error at least. Are you still getting the same after restarting the plugin on MM?

No, I double checked that, I'm very sure we are not mounting any volumes. And yes, even with the latest _v0.14.1_, that error remains.

> I think there could be an issue with the local DNS resolution for your rtcd host. It looks like the MM side may be getting the wrong IP address or the routing is not as expected.

I got into the EC2 instance which hosted MM, and checked the connectivity by running `curl http://rtcd.xxx:8045/version` . The version info was printed as expected. seems good?

> On a second thought, since the HTTP requests seem to be reaching just fine, I wonder if there could be something in between, like a proxy or load balancer that's not properly configured to handle websocket.

Do you mean websocket between MM and `rtcd` service?

**Comment by streamer45** [comment]
Thanks. I have a bit of a clearer picture of what's happening now. The `rtcd` side is resetting its state on restart as expected but the MM side is actually registering every time but failing to connect to Websocket.

> Do you mean websocket between MM and rtcd service?

Yeah, because the client is clearly connecting to the HTTP endpoint and registering but then it's failing to establish the Websocket connection with that "Not Found" error on dial, almost as something in between wasn't processing the request properly. 

One possible problem could be that MM and `rtcd` are not connecting directly but there's a third host in between, forwarding the requests.

**Comment by redfoxlee** [comment]
Hi, @streamer45 

Thanks for the reply!

I dug deeper and finally solved this issue. As you said, there was a proxy there that i didn't know (probably for the MM license activation, i guess). Problem solved once I appended `rtcd`'s domain to the _NO_PROXY_.

I confirmed connection has been established but it's unstable (connected and disconnected after about 15 seconds). Maybe a _TURN_ server is needed, but that's another problem. I think maybe i should create another ticket for that. Anyway, thank you very much for backing me up there!

I have some further questions to ask if it's okay (not sure this is the right place, if not please let me know).

* `rtcd`
    * Can it be clustered.
        * Dose this feature get effected from different user session on different node (for example: users in one room have to be logged in the same node)?
* `calls-offloader`
    * Can it be clustered?
    * Can it be dockerized (I noticed there was no docker file provided)

Thanks again!

**Comment by streamer45** [comment]
Glad to hear that part is solved.

> I confirmed connection has been established but it's unstable (connected and disconnected after about 15 seconds). Maybe a TURN server is needed, but that's another problem. 

Using a TURN server is fine but unless you (or your users) are behind a very strict firewall blocking all sorts of outgoing connections it should connect fine without. If it's dropping after 15 seconds it means the connection timeout fired and UDP connectivity is not achieved at all.

I'd start with making sure that data can be exchanged over UDP on the configured port (`ice_port_udp`). Since you are running in docker it may be worth checking that port forwarding is correctly configured to expose the port to the host and then make sure `ice_host_override` is also set to the client facing IP for the instance running `rtcd`.

> * `rtcd`
>    * Can it be clustered.

It's not designed to be clustered but it has support for some form of horizontal scaling through DNS. That's achieved by having multiple `rtcd` instances under the same hostname that you configure in the `RTCDServiceURL` plugin setting. The plugin will then resolve the host and randomly assign an instance to every new call. So the scaling effectively happens at the call level, not session. All sessions belonging to the same call will live on the same `rtcd` instance.

> * `calls-offloader`
>    * Can it be clustered?

Not yet but we are planning some work to make it horizontally scalable, similarly to `rtcd`.


>    * Can it be dockerized (I noticed there was no docker file provided)

Technically it can, but we don't officially support it as the service itself relies on the docker engine so you'd need a more complex setup (either docker-in-docker or docker-out-of-docker). That said, we have an internal service used for testing that runs this way so it's doable, just needs some extra care.

**Comment by redfoxlee** [comment]
Hi, @streamer45

Sorry for letting you wait!

I somehow managed to make it work with having both of client and server in the same VPC. For the incoming requests from outside the VPC, I even prepared a *coturn* for that, but i haven't succeeded yet. However I passed ICE servers to the `rtcd` through the environment variable `RTCD_RTC_ICESERVERS` in the form of JSON string like:
```json
[{"urls":["stun:ip:port"]},{"urls":["turn:ip:port"],username:"xx", "credential":"yy"}]

// there will be errors if i escaped the double quotes
[{\"urls\":[\"stun:ip:port\"]},{\"urls\":[\"turn:ip:port\"],\"username\":\"xx\", \"credential\":\"yy\"}]
```
and I observed its value has been printed in the `rtcd`'s log without errors. But it did not get passed to the client at all. If i set it on the plugin side, it will get passed to the client. Can you confirm that? Please let know if I did it wrong...

> It's not designed to be clustered but it has support for some form of horizontal scaling through DNS.

Sorry, `Clustered` was not a proper choice of words. *Horizontal Scaling* is good enough!

> Not yet but we are planning some work to make it horizontally scalable, similarly to `rtcd`.

Glad to hear it! Yes, please! We are also considering to provide this feature to our users. But we just don't know how to evaluate it. I mean do we need the scalability or not.

**Comment by streamer45** [comment]
@redfoxlee Glad to hear you made some good progress. Using TURN is fine but I wonder what the challenge is in exposing the `rtcd` host outside the VPC. To get clients outside to connect you need to have a reachable host whether it's TURN or `rtcd` but the latter would be more efficient.

> If i set it on the plugin side, it got passed to the client. Can you confirm that?

Yes, that's the way to go as TURN config is mostly meant for clients so needs to be configured on the plugin side. Configuring it on `rtcd` is only useful if you also want the server side connections to potentially make use of it (which will need server side TURN enabled but it's likely never needed). 

I now realize I gave you inaccurate information above which I've now fixed. So to re-cap, the following settings:

- `iceserversconfigs`
- `turncredentialsexpirationminutes`
- `turnstaticauthsecret`

Will need to be configured on the MM side so that TURN endpoint(s) and credentials are generated on the fly and correctly passed to clients when joining calls.

> We are also considering to provide this feature to our users. But we just don't know how to evaluate it. I mean do we need the scalability or not.

It will definitely benefit from horizontal scaling since call recordings jobs are especially demanding resource wise as they require real-time audio/video transcoding capabilities.

**Comment by redfoxlee** [comment]
Hi @streamer45 

> Glad to hear you made some good progress. Using TURN is fine but I wonder what the challenge is in exposing the rtcd host outside the VPC. To get clients outside to connect you need to have a reachable host whether it's TURN or rtcd but the latter would be more efficient.

Thanks! I'd like to share more details with you, but it's also a huge challenge to my english...trust me! 

However, we were trying to hold them (including the _TURN_ server) all in a same _VPC_ which is a little bit far away from the gateway. _webrtc_ was not in our knowledge-base, we had completely no idea what we were dealing with. So, we had to spend some time to do the homework. And there were also other _VPCs_ and couple uncleared routing paths, rules and waiting for approval to open ports (like you said it's indeed a restricted network).  It took us a lots of time. We've managed to make it work with _coturn_ on _TCP_ relaying mode (having clients outside the _VPC_, _TURN_ server is some where neutral between _VPCs_ to achieve the maximum connectivity), so far. We are still waiting for the approval for opening _UDP_ (_direct/indirect (relaying) UPD_ connections are still preferable). Hope it can go well.

> Will need to be configured on the MM side so that TURN endpoint(s) and credentials are generated on the fly and correctly passed to clients when joining calls.

Thanks for the re-cap and explanation! It's very important to know how it works. It would be nice to see this documented. I know it depends on the specific infrastructures though, but still it would be nice if you can provide some sorts of presets or recommendations like this, especially when they share same (optional) options on both sides. It's very easy to get confused.

I can see you also tried to make it more easy. But in fact hiding them only made me more confused (no idea why they'd gone). Here are some suggestions hope you can consider it.

- Hiding options on the fly on `RTCDServiceURL` change, so users would know it matters (and wonder how it matters, maybe...).
- Give users more hints to let them know where and why those options are gone and what should they do.
    - A popup message, maybe (it's probably the most easy way).
    - Or show more details in the *help_text* field (it needs more works).
    - Otherwise try to mention it in all relative options (if necessary).

> It will definitely benefit from horizontal scaling since call recordings jobs are especially demanding resource wise as they require real-time audio/video transcoding capabilities.

Ok, I think we need this! I'd like try it out once we solved this problem.

For now, I have no further questions to ask, I'll close this ticket.
Thank you very much for your patient and professional answers. Cheers!

**Comment by streamer45** [comment]
Thanks @redfoxlee , that's some great feedback. We have a quarter goal to improve our documentation so I'll make sure your concerns are addressed. I created https://mattermost.atlassian.net/browse/MM-52002 to keep track of this internally.

Closing this issue for now but feel free to reach out again if you need anything.

**Comment by redfoxlee** [comment]
Hi @streamer45 
Copy that!
Thanks!
