### ISSUE TITLE
Unable to connect to the voice call: timed out waiting for peer connection

### ISSUE THREAD

**Issue by davide-prade** [mattermost/mattermost-plugin-calls#451]
#### Summary
Cannot start/join to call

### Environment Information
  - Device Name: HUAWEI Mate 20 lite
  - OS Version: EMUI 12.0.0
  - Mattermost App Version: 2.4.0 (Build 6000465)
  - Mattermost Server Version: 7.9.2 (self-hosted)

#### Steps to reproduce
1. Open Mattermost app
2. Start call

#### Expected behavior
Calls started/joined successfully.

#### Observed behavior (that appears unintentional)
Cannot start/join the voice call. The following error appears: "**Unable to connect to the voice call: timed out waiting for peer connection**".
![Screenshot_20230516_121130](https://github.com/mattermost/mattermost-mobile/assets/22656675/f0c44ea3-5cf9-4584-8982-12dd958f2e19)

#### Possible fixes
No fix found.

**Comment by bguerin** [comment]
> @bguerin That's usually normal. Several candidates get advertised to clients, some of which are local and won't work. The important one to have clients connect from the outer internet is the main host candidate that's served through the RTC port.

Right, but what I'm describing is my cloud server sending packets to my 10.0.0.0/16 private, internal, LAN IP address of my laptop running the desktop app, and sending packets ONLY to that IP. And I mean the ` ip.dst` field, not something in the RTC layer. And obviously, a 10.0.0.0/16 IP address cannot be routed on the Internet

> Could you share your current config for the plugin?

```
 "com.mattermost.calls": {
                "allowenablecalls": false,
                "allowscreensharing": true,
                "defaultenabled": true,
                "enableipv6": false,
                "enablerecordings": false,
                "enableringing": true,
                "enablesimulcast": true,
                "icehostoverride": "chat.mydomain.tld",
                "iceservers": "stun:stun.global.calls.mattermost.com:3478",
                "iceserversconfigs": "[{\"urls\":[\"stun:stun.global.calls.mattermost.com:3478\"]}]",
                "jobserviceurl": null,
                "maxcallparticipants": 8,
                "maxrecordingduration": 60,
                "recordingquality": "medium",
                "rtcdserviceurl": null,
                "serversideturn": false,
                "tcpserveraddress": "",
                "tcpserverport": 8443,
                "turncredentialsexpirationminutes": 1440,
                "turnstaticauthsecret": "",
                "udpserveraddress": "",
                "udpserverport": 8443
}
```

**Comment by streamer45** [comment]
@bguerin Server will try to send packets to whatever IP the client is sharing, including local ones. Of course it won't ever receive back from those which is fine and expected. 

The problem seems to be that connectivity through `chat.mydomain.tld:8443` is not really working as it should because that's the path packets should normally take if the client is outside the local network. You said the port is open and correctly forwarded. Would you be able to verify that packets can flow through correctly with some simple checks using netcat?

Example:


On the MM instance, running:

```
nc -l -u 0.0.0.0 8443
```

Make sure to temporarily disable the plugin or it will likely fail to listen on the same port.

On your client (i.e. where the Desktop app runs):

```
nc -u -v chat.mydomain.tld 8443
```

That should connect successfully.

**Comment by bguerin** [comment]
@streamer45 test already done, I can `netcat`  to my server, on UDP port 8443

Connection from my client, on my home network (so NATed on Internet) to my cloud server is working
The reverse, cloud server to my client, is not

I known that a client may advertise several addresses. The weird thing here is that my **server** **only** responds to my **private home IP**, I **never** see packets sent to my public IP
My client keep trying connecting, and my server keep responding to a black hole

**Comment by streamer45** [comment]
@bguerin Does the netcat check work inside docker container as well? We had a few cases of people struggling to connect with docker setups due to some weird configurations on the internal network.

I think the best way to debug further would be for you to reach out to me directly on our [community server](https://community.mattermost.com/) so that we can more easily share information (logs/configs and such).

**Comment by streamer45** [comment]
I am closing this issue as the original reported has deemed it fixed. The problem was that some devices/networks were unable to connect through UDP (likely due to client-side firewall restrictions). Enabling TCP candidates (a new functionality introduced in recent version) made it possible for these devices to connect without resorting to a more complex setup involving a TURN server.

Feel free to open a separate issue if you encounter similar problems. Closing for now.

**Comment by heyValdemar** [comment]
I've successfully resolved the issue. The culprit was in the Traefik configuration.

For calls to function correctly, the following lines in the Traefik configuration are essential:

`      - "--entryPoints.calls.address=:8443/udp"`

`      - "8443:8443" `

```
      - "traefik.udp.routers.mm-call-rtr.service=mm-call-svc"
      - "traefik.udp.routers.mm-call-rtr.entrypoints=calls"
      - "traefik.udp.services.mm-call-svc.loadBalancer.server.port=8443"
      - "traefik.http.middlewares.compresstraefik.compress=true"
```

For a comprehensive look, you can view my entire Docker configuration [here](https://github.com/heyValdemar/mattermost-traefik-letsencrypt-docker-compose).
