### ISSUE TITLE
Mattermost supporting video calling

### ISSUE THREAD

**Issue by itsmichaelk** [mattermost/mattermost-plugin-calls#454]
Hello everyone,

we're close to fully migrate from Slack to Mattermost, but we really miss the option to use our webcams inside calls - is this on your todo list? Is this planned? Am I missing something? Can we get it in a beta state?

Thanks in advance!

**Comment by streamer45** [comment]
@itsmichaelk First of all, thanks for giving Mattermost a go :) I'll refer you to https://github.com/mattermost/mattermost-plugin-calls/issues/378 since it's essentially the same question.

But to add on that the hard truth is that video has always been on our minds but the lack of resources due to the recent economic downturn made it so that it was never prioritized and likely won't be on our official roadmap for a while.

That said, this project is technically open source and we have plenty of engineers that could give a hand so it's not completely outside the realm of possibility to see something happening on this front :crossed_fingers:

**Comment by streamer45** [comment]
Closing this as we are tracking it already but feel free to reach out again any time :+1:
