### ISSUE TITLE
Feature Request: Visual indicator on shared screens

### ISSUE THREAD

**Issue by gamerxD1998** [mattermost/mattermost-plugin-calls#617]
Hello,

a few months ago i migrated my workplace from skype to mattermost.

When sharing screens in calls there is no visual indicator on that screen unlike in skype (red border around the screen when shared).
Is it possible to implement something similar? I've got some complaints already about that missing feature as they sometimes seem to forget they are screensharing a specific screen. The small panel in the bottom left of mattermost just isn't visible enough for them.

**Comment by streamer45** [comment]
Hi, 

Thanks for the feedback! Last time I checked there wasn't a way to do this from the web application since that panel is a web browser security feature that cannot be controlled nor customized.

That said, I am thinking that this sort of functionality should be implementable on Desktop using native APIs but not something we are working on at the moment.
