### ISSUE TITLE
Error while updating 0.27 to 0.28.2

### ISSUE THREAD

**Issue by hagaygo** [mattermost/mattermost-plugin-calls#804]
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5015856/285de84c-8345-4e27-ba31-96eb5ab6f10c)

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5015856/21ce359f-9dc4-4560-97b9-084b738962c0)

Tried to remove the plugin and install it , same problem.

Any pointers ? 

Thanks

**Comment by streamer45** [comment]
@hagaygo What MySQL version are you running? The new plugin version uses dedicated SQL tables created automatically on the first upgrade. From the looks of it, the migration there is failing because of an internal error in your database engine (1728). 

It's worth checking https://stackoverflow.com/a/30224954 as a potential fix.

**Comment by hagaygo** [comment]
Our isntalled user maria db 10.X for some times , worked fine so far.
Switched to mysql and it seems to be working fine.
