### ISSUE TITLE
Understand the RTC composant

### ISSUE THREAD

**Issue by vbx** [mattermost/mattermost-plugin-calls#813]
Hello, I am trying to test the call plugin for Mattermost, and I would like to understand the RTC implementation.
I expected an exchange (offer + answer + ICE) via a signaling server, then browsers connect directly (p2p concept).
Why must the browser be able to connect to the RTC component ?
Thanks

**Comment by streamer45** [comment]
@vbx There's no p2p involved in our implementation, which relies on a [SFU](https://bloggeek.me/webrtcglossary/sfu/). That's why clients will never connect directly but always go through an intermediary RTC server, implemented by either the plugin or an external service (https://github.com/mattermost/rtcd).
